[workspace]
members = ["velox-wasm-macros", "velox-wasm-sdk", "examples/add"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
arrow-array = "59.1.0"
arrow-buffer = "59.1.0"
arrow-data = "59.1.0"
arrow-ipc = "59.1.0"
arrow-schema = "59.1.0"
arrow-select = "59.1.0"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "fold"] }
